#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  button1,        sensorTouch)
#pragma config(Sensor, dgtl2,  button2,        sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           M1,            tmotorVex393_HBridge, openLoop, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define EXERCISE_NUMBER 	3 //WHEN YOU FINISH EACH EXERCISE, INCREMENT THIS VALUE

bool button1_pushed; //flag to store button1 input
bool button2_pushed; //flag to store button2 input


/* monitorInput()
*
*  Used to flag button inputs
*       - Note that this function only sets button1_pushed and button2_pushed flags to true.
*         Your code should clear these flags by setting the appropriate variable to false after
*         the appropriate action has been taken.
*
*  Tips on use:
*       - The monitorInput function should be called periodically.
*				  - The function can only set the flags when it is called.
*       - Good practice is to continously call monitorInput and then check what flags have been set.
*         Take action corresponding to flag settings and then set the flags back to false to prevent
*         unwanted action repetitons.
*  Example: Code will execute action 1 once when button 1 is pushed.
*    while(1) {
*      monitorInput();
*      if ( button1_pushed ) {
*        action1();
*        button1_pushed = false;
*      }
*    }
*
*    The button1_pushed = false; line is required to stop code from endlessly
*    repeating action 1 after button is pushed.
*    The action will be repeated if the button is pushed again.
*/
void monitorInput()
{
	if(SensorValue(button1) && !button1_pushed)
	{
		button1_pushed = true;
	}

	if(SensorValue(button2) & !button2_pushed)
	{
		button2_pushed = true;
	}
}

void exercise_1()
{

	while(true)
	{
		monitorInput();
		if( button1_pushed ) {
			/* INSERT CODE HERE
			* - IMPORTANT: WHEN YOU SET UP YOUR PUSH BUTTONS, YOU MUST NAME THEM "button1"
			* - AND "button2" or you will get compiler errors when you attempt to run your code
			* - make sure EXERCISE_NUMBER is set to 1
			* - turn motor on and clear button1_pushed flag
			* - wait for button2 push
			* - turn motor off, and clear flag again
			*/
			motor[M1]=50;
			if(button2_pushed){
				motor[M1]=0;
				button1_pushed=false;
			}
			button2_pushed=false;
		} // end if
	}//end while
}

void exercise_2()
{
	while(true)
	{
		monitorInput();

		if(button1_pushed)
		{
			/* INSERT CODE HERE
			* - Make sure EXERCISE_NUMBER is set to 2
			* - reset rotation sensor
			* - turn motor on
			* - wait for rotation to reach 627
			* - turn motor off, and clear button1_pushed flag
			*/
			resetMotorEncoder(M1);
			while(getMotorEncoder(M1) < 627){
				motor[M1]=50;
			}

			motor[M1]=0;
			button1_pushed=false;


		} // end if
	}// end while

} // end exe

void exercise_3()
{
	button1_pushed = false;
	button2_pushed = false;
	int Case=1; //case variable for Finite State

	while(true)
	{
		monitorInput();

		switch (Case)
		{

		case 1: //motor off, monitors for buttons being pressed

			motor[M1]=0;
			if (button1_pushed){
				Case=2;

			}

			if (button2_pushed){
				Case=4;

			}

			break;
		case 2: // button 1 pressed motor forward
			button1_pushed=false;
			resetMotorEncoder(M1);
			while(getMotorEncoder(M1) < 3000){
				motor[M1]=50;

				monitorInput();
				button1_pushed=false;
			}


			Case=1;

			break;


		case 4:// if button 2 pressed motor reverse
			button2_pushed=false;
			resetMotorEncoder(M1);
			while(getMotorEncoder(M1) > -3000){
				motor[M1]=-50;

				monitorInput();
				button2_pushed=false;
			}

			Case=1;

			break;


		}//end case
	}//end while

}//end exercse_3


task main()
{
	button1_pushed = button2_pushed = false;

	switch (EXERCISE_NUMBER)
	{
	case 1:
		exercise_1();
		break;
	case 2:
		exercise_2();
		break;
	case 3:
		exercise_3();
		break;
	default: //should never get here.
	} // end switch

}// end main
